### ISSUE TITLE
Any plan to release APK version?

### ISSUE THREAD

**Issue by owen800q** [Talaxy009/Moedaily#1]
Hi @Talaxy009 

Any plan to release a APK version?

**Comment by Talaxy009** [comment]
Thanks for your concern ☺️. I am preparing to put it on the Google play store. I may submit it for review and release the first version on GitHub in two days.

**Comment by owen800q** [comment]
Cool, thank you

**Comment by Talaxy009** [comment]
The play store sent me a email about the review of alpha version, it seem that I can only publish Moedaily on Github for now 😢. Btw the first version has been release ☺️, you can download from [here](https://github.com/Talaxy009/Moedaily/releases).
![image](https://user-images.githubusercontent.com/41264828/219940782-a4257ccf-351c-4e75-8f7d-02ebaa094895.png)
